version: '2'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

  jaegertracing:
    image: jaegertracing/all-in-one:1.16.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

volumes:
  redis_data:
    driver: local